### ISSUE TITLE
Totem of holding 

### ISSUE THREAD

**Issue by GamingGrandma** [lucidobservor/floramancer-modpack#10]
I used to be able to left click on the totem on holding to get my stuff back.  This no longer works.  I can't break it, can't left click or right-click...I can't seem to get it to work

**Comment by Ctfurlani** [comment]
Hello. You can do as follow:
Go into mod options > quark > oddities > totem of holding > allow anyone to collect.
This should allow you to collect it

**Comment by lucidobservor** [comment]
Fixed in most recent pack update
