### ISSUE TITLE
Dispenser Planting Floating Generating flower

### ISSUE THREAD

**Issue by Markedfordeletion** [lucidobservor/floramancer-modpack#11]
When using a dispenser to plant a Floating Munchdew i got a Floating Botania flower that says "If you have this, it means something is wrong, you should report it"

**Comment by Winrylive** [comment]
Congrats, you've found Vazkii's intentional Easter egg. No need to report this, tbh. Just don't use dispensers to place generating flowers. Look at using the Rannuncarpus instead.
