### ISSUE TITLE
Totem of holding

### ISSUE THREAD

**Issue by Ctfurlani** [lucidobservor/floramancer-modpack#4]
Hello, I died after the new update and can't get my stuff back from the totem. Tried left clicking, right clicking, shifting. Thanks.

**Comment by lucidobservor** [comment]
You collect items from the totem by left clicking it several times, until it disappears. If you didn't have many items in your inventory, the first couple clicks may not appear to do anything. Try clicking multiple times and that may resolve your issue.

If you still cannot collect your items, please open another issue and I'll look into it further.
