### ISSUE TITLE
Pethal Apothecary

### ISSUE THREAD

**Issue by GabumonSilver** [lucidobservor/floramancer-modpack#7]
Hello, I will be direct ....: I was doing a "Pure Daisy" try to make the petals fall in the petoteca apotecary but they just ran around (not inside it) and try with the category of mushrooms nothing neither. Also with dispensers or dropers.

**Comment by Winrylive** [comment]
Did you put water in it first? They don't enter the apothecary until there is water in it.

**Comment by lucidobservor** [comment]
Winry's question seems to me like the most likely reason for what's going wrong. If that's not the case, then I'm going to need pictures or a better explanation of what you're struggling with.
